### ISSUE TITLE
Cannot start iPerf test service 

### ISSUE THREAD

**Issue by zeeshanjahangir** [openbaton/integration-tests#4] opened 2017-07-05 18:59 UTC
Following error observed while lauching a service 

VIM instance name = orchestrator 

ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to allocate Resources because: org.openbaton.exceptions.VimException: Not launched VM with hostname iperf-server-4600127 successfully on VimInstance Orchestrator. Caused by: org.openbaton.exceptions.VimDriverException: Not found Network 'private'. Consider to refresh the VIM manually and try again ...

**Comment by lorenzotomasini** [comment] 2017-07-06 08:05
Hi @zeeshanjahangir ,

Most of the time this error appears if the openstack environment is changed underneath Open Baton, for instance a new network is created but the Vim is not refreshed.

Is there a network called _private_ in the tenant where OB points to? if yes then try to refresh the vim instance (manage pops --> vim instances --> click on id of the vim --> click on the refresh button close to the vim name). After this you should be able to see in the network list the _private_ one. 

If there is no network called _private_ in the openstack tenant you are trying to deploy and it is not created while deploying, we would need the nfvo and openstack plugin logs in order to find the issue

**Comment by mf3d3r** [comment] 2017-09-20 13:37
Well, I'm facing the same issue with the same error within the iperf tutorial. I tried the SIP tutorial as well and surprisingly got the same error message again.

_"... Not able to allocate Resources because: ... Not found Network 'private'. Consider to refresh the VIM manually and try again ..."_

I followed the Docker-Approach. NFVO,generic VNFM,OpenStack Vim Driver are up. OpenStack also works, I have connectivity between OB and OS. When launching the uploaded NS, I can watch at OS that Routers, Networks, Subnets are created, but the Instances are not coming up following by the error output above in OB NS-Record. 

The error message says that a network "private" can not be found. But this network "private" is created and deployed during the launching process by the NSD itself. If you need some log file outputs just let me know.

Confusing for beginners is as well that there is a "configured and running OS Environment needed for each tutorial". But what das configured and running means exactly. To which grade it has to be configured that the tutorials work fine?

**Comment by gc4rella** [comment] 2017-09-22 10:24
hi all, just to be sure, are those issues related with the execution of integration tests, or with standalone deployments done via dashboard or CLI? In the second case, I would appreciate if you could open such issues on the NFVO issue board (https://github.com/openbaton/NFVO)

Anyway, @mf3d3r yes would be great if you could provide the logs of the openstack-plugin as well as the nfvo. Please provide also the version you are currently using (it should be displayed on the bottom part of the dashboard). 

> Confusing for beginners is as well that there is a "configured and running OS Environment needed for each tutorial". But what das configured and running means exactly. To which grade it has to be configured that the tutorials work fine?

Yes, I agree with you. Infact, I've already started extending and improving the documentation. You may see it on https://github.com/openbaton/docs/tree/develop, in particular https://github.com/openbaton/docs/blob/develop/docs/openstack-driver.md should describe the prerequisites needed for tutorials using openstack. 

As for all open source projects, this is a collaborative work. So, I would appreciate any pull request that you think may be improving the current documentation. Thank you.

**Comment by mf3d3r** [comment] 2017-10-02 10:43
Hi @gc4rella,
gladly I will make a pull request for improving the documentation, but first I need to start at least one tutorial without errors. You can see my error description during the iperf-tut on the NFVO issue board. I really would appreciate some help...

**Comment by gc4rella** [comment] 2017-10-02 10:52
@mf3d3r just commented your issue, I hope with the change I suggested you get finally a working environment ;-)
I'll close this issue here as duplicated.

**Closed by gc4rella** 2017-10-02 10:52 UTC

**Comment by zqtdd** [comment] 2019-12-11 03:06
ERROR:org.openbaton.common.vnfm_sdk.exception.VnfmSdkException: Not able to grant operation because: Not created Network with name: private successfully on VimInstance test1. Caused by: org.openbaton.exceptions.VimDriverException: Service Unavailable
